#
###################################
# Hi! Welcome to blog of 曾许曌秋 #
#################################
#
# This config file is meant for settings that affect the whole blog, values
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site info
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.zxzq.me" # the base hostname & protocol for your site, e.g. http://example.com
SEOTitle: 曾许曌秋的博客 | blog of Sorakaru
description: >- # this means to ignore newlines until next one
  This is blog of 曾许曌秋, enjoy!
keywords:
avatar: /images/rain.jpg
header-img: /images/30.jpg

# Follow
email: 1312660923@qq.com
phpurl: zxzq.me # by default: https:// (can be changed in _include/follow.html)
php-favicon: https://zxzq.me/images/favicon.ico
twitter-usrname:  bllovetx
github-usrname:   bllovetx
zhihu-usrname:    bllovetx
linkedin-usrname: bllovetx

# float
floatimg: /images/megumin.gif
hito: on


# Build settings
markdown: kramdown
permalink: pretty
# #theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag



friends: [
  {
    title: "testing",
    url: "https://test.zxzq.me"
  }
]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
